// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace iNTEGRA_Wilber_Jorge.Models
{
    public partial class Empleados
    {
        [Key]
        public int IdEmpleado { get; set; }

        [Required]
        [StringLength(60)]
        public string Apellidos { get; set; }

        [Required]
        [StringLength(60)]
        public string Nombres { get; set; }

        [Required]
        [StringLength(20)]
        public string Telefono { get; set; }

        [Required]
        [StringLength(100)]
        public string Correo { get; set; }

        [Required]
        [StringLength(150)]
        public string Foto { get; set; }

        [Column(TypeName = "date")]
        public DateTime FechaContratacion { get; set; }
    }
}