// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using iNTEGRA_Wilber_Jorge.Models;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace iNTEGRA_Wilber_Jorge.Data
{
    public partial class Prueba_IntegraContext : DbContext
    {
        public Prueba_IntegraContext()
        {
        }

        public Prueba_IntegraContext(DbContextOptions<Prueba_IntegraContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Empleados> Empleados { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=Prueba_iNTEGRA;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Empleados>(entity =>
            {
                entity.HasKey(e => e.IdEmpleado)
                    .HasName("PK__empleado__88B51394823786EF");

                entity.ToTable("empleados");

                entity.HasIndex(e => e.Telefono, "UQ__empleado__2A16D945BBB07700")
                    .IsUnique();

                entity.HasIndex(e => e.Correo, "UQ__empleado__2A586E0B3D435132")
                    .IsUnique();

                entity.Property(e => e.IdEmpleado).HasColumnName("id_empleado");

                entity.Property(e => e.Apellidos)
                    .IsRequired()
                    .HasMaxLength(60)
                    .IsUnicode(false)
                    .HasColumnName("apellidos");

                entity.Property(e => e.Correo)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("correo");

                entity.Property(e => e.FechaContratacion)
                    .HasColumnType("date")
                    .HasColumnName("fecha_contratacion");

                entity.Property(e => e.Foto)
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnName("foto");

                entity.Property(e => e.Nombres)
                    .IsRequired()
                    .HasMaxLength(60)
                    .IsUnicode(false)
                    .HasColumnName("nombres");

                entity.Property(e => e.Telefono)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("telefono");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}